import { StyleSheet } from 'react-native';
import { c, font } from './theme';

export const styles = StyleSheet.create({
  screenRoot: { flex: 1, backgroundColor: c.surface50 },
  header: { height: 58, flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 16, backgroundColor: c.white, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: c.surface200, shadowColor: c.surface900, shadowOpacity: 0.04, shadowRadius: 10, elevation: 2 },
  headerBack: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 12 },
  headerTitle: { flex: 1, fontSize: 18 },
  headerActions: { gap: 8, flexShrink: 0 },
  headerUtilityActions: { gap: 8 },
  bottomNav: { position: 'absolute', left: 10, right: 10, backgroundColor: c.white, borderWidth: 1, borderColor: c.surface200, borderRadius: 28, flexDirection: 'row', justifyContent: 'space-between', gap: 2, paddingTop: 9, paddingHorizontal: 6, shadowColor: c.surface950, shadowOpacity: 0.14, shadowRadius: 24, shadowOffset: { width: 0, height: 10 }, elevation: 14 },
  bottomNavItem: { flex: 1, minWidth: 0, minHeight: 52, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 2, paddingVertical: 6, borderRadius: 18 },
  bottomNavItemActive: { backgroundColor: c.formalio50 },
  bottomNavAddItem: { transform: [{ translateY: -18 }], minHeight: 52 },
  bottomNavLabel: { fontSize: 9.5, lineHeight: 12, marginTop: 3, textAlign: 'center' },
  addTab: { width: 54, height: 54, borderRadius: 27, alignItems: 'center', justifyContent: 'center', backgroundColor: c.formalio700, shadowColor: c.formalio900, shadowOpacity: 0.24, shadowRadius: 18, shadowOffset: { width: 0, height: 10 }, elevation: 9 },
  card: { backgroundColor: c.white, borderRadius: 18, borderWidth: 1, borderColor: c.surface200, padding: 14, shadowColor: c.surface900, shadowOpacity: 0.04, shadowRadius: 8, shadowOffset: { width: 0, height: 2 }, elevation: 1 },
  row: { flexDirection: 'row', alignItems: 'center' },
  pill: { alignSelf: 'flex-start', borderRadius: 999, paddingHorizontal: 8, paddingVertical: 4 },
  primaryButton: { minHeight: 54, borderRadius: 18, alignItems: 'center', justifyContent: 'center', borderWidth: 1, paddingHorizontal: 14, overflow: 'hidden', position: 'relative', shadowColor: c.formalio900, shadowOpacity: 0.08, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 2 },
  primaryButtonFill: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, borderWidth: 1 },
  primaryButtonFillDisabled: { opacity: 1 },
  primaryButtonContent: { justifyContent: 'center', gap: 8, minWidth: 0, zIndex: 1, paddingVertical: 6 },
  primaryButtonDisabled: { shadowOpacity: 0, elevation: 0 },
  authFull: { flex: 1, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  decorativeOrb: { position: 'absolute', width: 260, height: 260, borderRadius: 180 },
  softOrb: { position: 'absolute', width: 150, height: 150, borderRadius: 100 },
  authShell: { flex: 1 },
  welcomeScreen: { flexGrow: 1, justifyContent: 'space-between' },
  welcomeCenter: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24 },
  welcomeTitle: { marginTop: 26, textAlign: 'center', fontSize: 24, lineHeight: 30 },
  welcomeCopy: { marginTop: 12, maxWidth: 310, textAlign: 'center', color: c.surface500, fontSize: 14, lineHeight: 21 },
  chipWrap: { marginTop: 22, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 8 },
  chipWrapLeft: { marginTop: 8, flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  welcomeActions: { paddingHorizontal: 24, paddingTop: 14, gap: 12, backgroundColor: c.white, borderTopWidth: 1, borderTopColor: c.surface100, shadowColor: c.surface900, shadowOpacity: 0.06, shadowRadius: 18, shadowOffset: { width: 0, height: -8 }, elevation: 8 },
  authPrimaryButton: { width: '100%', minHeight: 56, shadowOpacity: 0.16, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  authSecondaryButton: { width: '100%', minHeight: 54, borderColor: c.formalio200, backgroundColor: c.white, shadowColor: c.surface900, shadowOpacity: 0.05, shadowRadius: 12, elevation: 2 },
  dot: { width: 8, height: 8, borderRadius: 999, backgroundColor: c.surface200 },
  dotActive: { width: 32, backgroundColor: c.formalio700 },
  formScreen: { flexGrow: 1, padding: 24, paddingBottom: 32 },
  formScreenCompact: { paddingTop: 18, paddingBottom: 24 },
  authFormStack: { marginTop: 24, gap: 15 },
  authBack: { width: 40, height: 40, borderRadius: 20, backgroundColor: c.surface50, alignItems: 'center', justifyContent: 'center', marginBottom: 18 },
  authTitle: { fontSize: 24, lineHeight: 31, marginTop: 20 },
  authSubtitle: { color: c.surface500, fontSize: 14, marginTop: 5, lineHeight: 20 },
  segment: { width: '100%', backgroundColor: c.surface100, borderRadius: 14, borderWidth: 1, borderColor: c.surface100, padding: 5, overflow: 'hidden' },
  segmentTrack: { flexDirection: 'row', alignItems: 'stretch', gap: 5 },
  segmentTrackFill: { width: '100%' },
  segmentTrackCompact: { gap: 3 },
  segmentTrackAndroidTight: { gap: 0 },
  segmentScrollContent: { flexDirection: 'row', gap: 5 },
  segmentTap: { flex: 1, minWidth: 0 },
  segmentTapScrollable: { flex: 0, minWidth: 104 },
  segmentItem: { width: '100%', borderRadius: 11, minHeight: 44, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 5, paddingHorizontal: 8, position: 'relative', overflow: 'hidden' },
  segmentItemCompact: { gap: 4, paddingHorizontal: 6 },
  segmentAndroidSlot: { flex: 1, minWidth: 0 },
  segmentAndroidCell: { width: '100%', minWidth: 0, minHeight: 42, borderRadius: 11, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 2, position: 'relative', overflow: 'hidden' },
  segmentAndroidCellSelected: { backgroundColor: c.white, shadowColor: c.surface900, shadowOpacity: 0.06, shadowRadius: 5, shadowOffset: { width: 0, height: 1 }, elevation: 1 },
  segmentLabel: { fontSize: 10.5, lineHeight: 14, textAlign: 'center', flexShrink: 1 },
  segmentLabelCompact: { fontSize: 10, lineHeight: 13 },
  segmentLabelAndroidTight: { width: '100%', fontSize: 9.4, lineHeight: 12, letterSpacing: 0 },
  segmentSelected: { backgroundColor: c.white, shadowColor: c.surface900, shadowOpacity: 0.06, shadowRadius: 5, shadowOffset: { width: 0, height: 1 }, elevation: 1 },
  segmentGlow: { position: 'absolute', left: 12, right: 12, bottom: 0, height: 2, borderRadius: 2, backgroundColor: c.formalio400 },
  segmentAndroidGlow: { position: 'absolute', left: 8, right: 8, bottom: 0, height: 2, borderRadius: 2, backgroundColor: c.formalio400 },
  segmentGlowCompact: { left: 8, right: 8 },
  inputBox: { minHeight: 58, borderRadius: 18, backgroundColor: c.surface50, borderWidth: 2, borderColor: c.surface100, paddingHorizontal: 14, paddingVertical: 14, flexDirection: 'row', alignItems: 'center', gap: 9 },
  inputBoxFocused: { borderColor: c.formalio300, backgroundColor: c.white, shadowColor: c.formalio900, shadowOpacity: 0.08, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 2 },
  calculatedInputBox: { borderColor: c.info100, backgroundColor: c.info50 },
  textInput: { flex: 1, minHeight: 30, color: c.surface900, fontFamily: font.medium, fontSize: 15, lineHeight: 21, paddingVertical: 2, paddingHorizontal: 0, includeFontPadding: false },
  fieldLabel: { color: c.surface700, fontSize: 12, marginBottom: 6 },
  vDivider: { width: 1, height: 20, backgroundColor: c.surface300 },
  dividerLine: { flex: 1, height: 1, backgroundColor: c.surface200 },
  strengthBar: { flex: 1, height: 6, borderRadius: 6 },
  biometricLoginCard: { borderRadius: 20, borderWidth: 1, borderColor: c.formalio200, backgroundColor: c.formalio50, padding: 13, gap: 12, shadowColor: c.formalio900, shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 2 },
  biometricLoginIcon: { width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: c.white, borderWidth: 1, borderColor: c.formalio100 },
  biometricLoginButton: { minHeight: 46, borderColor: c.formalio200, backgroundColor: c.white },
  biometricCircle: { width: 128, height: 128, borderRadius: 64, backgroundColor: c.formalio50, alignItems: 'center', justifyContent: 'center', marginTop: 60 },
  successScreen: { flexGrow: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  welcomeBackCard: { width: '100%', marginTop: 24, padding: 18, borderColor: c.formalio200, shadowColor: c.formalio900, shadowOpacity: 0.08, shadowRadius: 14, elevation: 3 },
  welcomeBackRow: { justifyContent: 'space-between', gap: 12, minHeight: 38, paddingVertical: 6, borderTopWidth: 1, borderTopColor: c.surface100 },
  checkBig: { width: 80, height: 80, borderRadius: 40, backgroundColor: c.formalio100, alignItems: 'center', justifyContent: 'center', marginTop: 20 },
  otpBox: { width: 48, height: 58, borderRadius: 17, backgroundColor: c.surface50, borderWidth: 1, borderColor: c.surface200, textAlign: 'center', fontFamily: font.bold, fontSize: 21, color: c.surface900, paddingVertical: 8 },
  bubble: { position: 'absolute', backgroundColor: c.white, borderWidth: 1, borderColor: c.surface200, borderRadius: 16, paddingHorizontal: 12, paddingVertical: 8, shadowColor: c.surface900, shadowOpacity: 0.08, shadowRadius: 12, elevation: 2 },
  halo: { position: 'absolute' },
  toastHost: { position: 'absolute', left: 0, right: 0, zIndex: 300, alignItems: 'center', paddingHorizontal: 16, gap: 8 },
  toast: { width: '100%', maxWidth: 390, borderRadius: 18, padding: 14, flexDirection: 'row', gap: 10, alignItems: 'flex-start', shadowColor: c.surface950, shadowOpacity: 0.18, shadowRadius: 24, shadowOffset: { width: 0, height: 10 }, elevation: 9 },
  valueTrack: { height: 8, borderRadius: 99, overflow: 'hidden' },
  valueFill: { height: '100%', borderRadius: 99 },
  headerSpacer: { width: 40 },
  avatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: c.formalio100, borderWidth: 2, borderColor: c.white, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', shadowColor: c.surface900, shadowOpacity: 0.08, shadowRadius: 8, elevation: 2 },
  iconButton: { width: 40, height: 40, borderRadius: 12, backgroundColor: c.white, borderWidth: 1, borderColor: c.surface200, alignItems: 'center', justifyContent: 'center' },
  notificationDot: { position: 'absolute', top: 8, right: 8, width: 8, height: 8, borderRadius: 4, backgroundColor: c.danger500 },
  offlineBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 8, paddingVertical: 5, borderRadius: 9, backgroundColor: c.amber50 },
  modeToggle: { minWidth: 74, height: 40, borderRadius: 14, borderWidth: 1, borderColor: c.formalio200, backgroundColor: c.formalio50, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, paddingHorizontal: 9 },
  modeToggleOffline: { borderColor: c.amber200, backgroundColor: c.amber50 },
  balanceCard: { borderRadius: 26, padding: 20, marginBottom: 16, overflow: 'hidden', shadowColor: c.surface900, shadowOpacity: 0.16, shadowRadius: 20, shadowOffset: { width: 0, height: 10 }, elevation: 6 },
  balancePill: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: 'rgba(255,255,255,.1)', paddingHorizontal: 8, paddingVertical: 5, borderRadius: 9 },
  balanceDetail: { flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: 'rgba(255,255,255,.1)', paddingHorizontal: 12, paddingVertical: 5, borderRadius: 9 },
  dashboardQuickRow: { flexDirection: 'row', alignItems: 'stretch', width: '100%', marginBottom: 2 },
  dashboardQuickCell: { flex: 1, minWidth: 0 },
  dashboardQuickCellGap: { marginRight: 6 },
  quickAction: { minHeight: 106, backgroundColor: c.white, borderWidth: 1, borderColor: c.surface200, borderRadius: 18, paddingHorizontal: 8, paddingVertical: 12, alignItems: 'center', justifyContent: 'center', shadowColor: c.surface900, shadowOpacity: 0.08, shadowRadius: 14, shadowOffset: { width: 0, height: 5 }, elevation: 3 },
  quickActionCompact: { minHeight: 90, borderRadius: 16, paddingHorizontal: 4, paddingVertical: 9 },
  quickActionUltraCompact: { minHeight: 84, borderRadius: 15, paddingHorizontal: 3, paddingVertical: 8 },
  quickIcon: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center', marginBottom: 8 },
  quickIconCompact: { width: 32, height: 32, borderRadius: 11, marginBottom: 6 },
  quickValue: { fontSize: 15, lineHeight: 18 },
  quickValueCompact: { fontSize: 12, lineHeight: 15, textAlign: 'center' },
  quickLabel: { color: c.surface500, fontSize: 10, lineHeight: 13, marginTop: 3 },
  quickLabelCompact: { fontSize: 8.5, lineHeight: 11, textAlign: 'center' },
  actionCard: { minHeight: 78, flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: c.white, borderRadius: 18, borderWidth: 1, borderColor: c.surface200, padding: 14, shadowColor: c.surface900, shadowOpacity: 0.035, shadowRadius: 10, shadowOffset: { width: 0, height: 3 }, elevation: 1 },
  actionIcon: { width: 44, height: 44, borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
  aiAccounting: { borderRadius: 18, padding: 16, marginBottom: 16, overflow: 'hidden', shadowColor: c.surface900, shadowOpacity: 0.12, shadowRadius: 16, elevation: 5 },
  aiIconBox: { width: 48, height: 48, borderRadius: 18, backgroundColor: 'rgba(255,255,255,.15)', alignItems: 'center', justifyContent: 'center' },
  newBadge: { backgroundColor: c.gold500, borderRadius: 999, paddingHorizontal: 6, paddingVertical: 2 },
  mosikaTip: { flexDirection: 'row', gap: 12, borderRadius: 18, borderWidth: 1, borderColor: c.formalio200, backgroundColor: c.formalio50, padding: 14 },
  ficheReminderCard: { marginTop: 16, borderRadius: 18, borderWidth: 1, borderColor: c.amber500, backgroundColor: c.amber100, padding: 14 },
  ficheReminderIcon: { width: 42, height: 42, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: c.gold50 },
  ficheReminderButton: { alignSelf: 'flex-start', marginTop: 10, borderRadius: 999, borderWidth: 1, borderColor: c.amber500, backgroundColor: c.gold50, paddingHorizontal: 12, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', gap: 3 },
  transactionRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, paddingVertical: 10, paddingHorizontal: 8 },
  transactionIcon: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  stockValueCard: { borderColor: c.info100, backgroundColor: c.info50, padding: 16 },
  stockValueLink: { alignSelf: 'flex-start', marginTop: 12, minHeight: 36, borderRadius: 999, backgroundColor: c.white, borderWidth: 1, borderColor: c.info100, paddingHorizontal: 12, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', gap: 4 },
  stockHeaderCard: { borderColor: c.formalio100, backgroundColor: c.white, padding: 15 },
  stockEmbeddedHeader: { borderColor: c.formalio100, backgroundColor: c.formalio50, padding: 15 },
  stockAddButton: { minHeight: 42, minWidth: 104, borderRadius: 14, paddingHorizontal: 12, flexShrink: 0 },
  stockEmptyState: { alignItems: 'center', borderRadius: 18, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.white, paddingHorizontal: 22, paddingVertical: 34 },
  stockEmptyButton: { marginTop: 14, minHeight: 40, borderRadius: 13, backgroundColor: c.formalio700, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14 },
  stockItemCard: { gap: 12, padding: 12 },
  stockItemCardMuted: { backgroundColor: c.surface50 },
  stockItemIcon: { width: 38, height: 38, borderRadius: 13, backgroundColor: c.formalio50, alignItems: 'center', justifyContent: 'center' },
  stockIconButton: { width: 34, height: 34, borderRadius: 11, backgroundColor: c.info50, borderWidth: 1, borderColor: c.info100, alignItems: 'center', justifyContent: 'center' },
  stockDeleteButton: { backgroundColor: c.danger50, borderColor: c.danger100 },
  stockMetaCell: { minHeight: 64, borderRadius: 13, borderWidth: 1, borderColor: c.surface100, backgroundColor: c.surface50, padding: 9, justifyContent: 'center' },
  stockMetaLabel: { color: c.surface400, fontSize: 9.5, marginBottom: 3 },
  stockMetaValue: { color: c.surface800, fontSize: 10.5, lineHeight: 14 },
  stockFlagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  stockSalePanel: { gap: 8, borderRadius: 18, borderWidth: 1, borderColor: c.formalio100, backgroundColor: c.formalio50, padding: 12 },
  stockSaleList: { gap: 8 },
  stockSaleOption: { minHeight: 58, borderRadius: 14, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.white, padding: 11, justifyContent: 'center' },
  stockSaleOptionSelected: { borderColor: c.formalio400, backgroundColor: c.white },
  stockSaleOptionDisabled: { minHeight: 50, borderRadius: 14, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.surface100, padding: 11, justifyContent: 'center' },
  autoCalcHint: { alignItems: 'flex-start', gap: 7, borderRadius: 14, borderWidth: 1, borderColor: c.info100, backgroundColor: c.info50, paddingHorizontal: 11, paddingVertical: 9 },
  lockedFieldBadge: { gap: 4, flexShrink: 1, borderRadius: 999, backgroundColor: c.white, borderWidth: 1, borderColor: c.info100, paddingHorizontal: 8, paddingVertical: 5 },
  paymentMethodInline: { flexDirection: 'row', alignItems: 'center', gap: 5, minWidth: 0, flexShrink: 1 },
  paymentMethodMiniIcon: { borderWidth: 1, borderColor: c.surface100, shadowColor: c.surface900, shadowOpacity: 0.04, shadowRadius: 4, elevation: 1 },
  paymentBrandPill: { paddingLeft: 6, paddingRight: 9, paddingVertical: 5 },
  filterIconActive: { borderColor: c.formalio200, backgroundColor: c.formalio50 },
  filterActiveDot: { position: 'absolute', top: 7, right: 7, width: 7, height: 7, borderRadius: 4, backgroundColor: c.formalio600 },
  filterPanel: { gap: 13, borderRadius: 18, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.white, padding: 13, marginBottom: 14 },
  filterChip: { minHeight: 34, borderRadius: 999, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.surface50, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center' },
  filterChipActive: { borderColor: c.formalio300, backgroundColor: c.formalio50 },
  noResultsState: { alignItems: 'center', borderRadius: 18, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.white, paddingHorizontal: 24, paddingVertical: 42 },
  clearFiltersButton: { marginTop: 14, borderRadius: 999, borderWidth: 1, borderColor: c.formalio200, backgroundColor: c.formalio50, paddingHorizontal: 14, paddingVertical: 9 },
  loanCard: { flexDirection: 'row', gap: 12, borderRadius: 18, borderWidth: 1, borderColor: c.gold200, backgroundColor: c.gold50, padding: 14, marginBottom: 4 },
  loanIcon: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: c.gold100 },
  loanButton: { alignSelf: 'flex-start', backgroundColor: c.gold500, borderRadius: 9, paddingHorizontal: 12, paddingVertical: 7, marginTop: 9 },
  aiFabDock: { position: 'absolute', right: 18, width: 74, height: 74, alignItems: 'center', justifyContent: 'center', zIndex: 120, elevation: 30 },
  aiFabTouchable: { width: '100%', height: '100%', alignItems: 'center', justifyContent: 'center' },
  aiFab: { width: 58, height: 58, borderRadius: 29, backgroundColor: c.white, alignItems: 'center', justifyContent: 'center', shadowColor: c.surface950, shadowOpacity: 0.24, shadowRadius: 22, shadowOffset: { width: 0, height: 11 }, elevation: 24 },
  aiFabInner: { width: 50, height: 50, borderRadius: 25, alignItems: 'center', justifyContent: 'center' },
  aiFabBadge: { position: 'absolute', right: -2, top: -4, backgroundColor: c.gold500, borderRadius: 999, paddingHorizontal: 6, paddingVertical: 2 },
  transactionPreview: { flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 18, borderWidth: 1, padding: 13 },
  transactionPreviewIcon: { width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  ocrAutofillCard: { borderRadius: 18, borderWidth: 1, borderColor: c.info200, backgroundColor: c.info50, padding: 13 },
  ocrAutofillCell: { borderRadius: 12, borderWidth: 1, borderColor: c.info100, backgroundColor: c.white, padding: 10 },
  ocrRetryButton: { flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: 999, backgroundColor: c.white, borderWidth: 1, borderColor: c.surface200, paddingHorizontal: 10, paddingVertical: 7 },
  addTransactionActions: { gap: 12, marginTop: 8, paddingBottom: 36 },
  formActionButton: { minHeight: 52, borderRadius: 16 },
  ficheIntroCard: { alignItems: 'flex-start', gap: 12, padding: 18 },
  ficheIntroIcon: { width: 54, height: 54, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: c.formalio50, borderWidth: 1, borderColor: c.formalio100 },
  ficheIntroTitle: { color: c.surface900, fontSize: 20 },
  ficheIntroCopy: { color: c.surface600, fontSize: 13, lineHeight: 20 },
  ficheIntroMeta: { gap: 6, borderRadius: 14, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.surface50, padding: 12, width: '100%' },
  ficheIntroMetaText: { color: c.surface700, fontSize: 12 },
  fichePendingCard: { width: '100%', borderRadius: 14, borderWidth: 1, borderColor: c.amber500, backgroundColor: c.amber100, padding: 12 },
  ficheDocsSection: { gap: 12, marginBottom: 18 },
  ficheBatchButton: { minHeight: 36, borderRadius: 999, borderWidth: 1, borderColor: c.formalio200, backgroundColor: c.formalio50, paddingHorizontal: 12, flexDirection: 'row', gap: 6, alignItems: 'center', justifyContent: 'center' },
  ficheDocsEmpty: { alignItems: 'center', borderRadius: 18, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.white, paddingHorizontal: 20, paddingVertical: 28 },
  ficheDocCard: { gap: 12, padding: 13 },
  ficheDocAction: { minHeight: 40, borderRadius: 12, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.surface50, alignItems: 'center', justifyContent: 'center', gap: 4 },
  ficheContinueButton: { alignSelf: 'flex-start', borderRadius: 999, borderWidth: 1, borderColor: c.amber500, backgroundColor: c.amber100, paddingHorizontal: 12, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', gap: 4 },
  fichePreviewHero: { borderRadius: 22, padding: 16, overflow: 'hidden' },
  retraitDestinationCard: { minHeight: 122, borderRadius: 16, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.white, alignItems: 'center', justifyContent: 'center', gap: 6, padding: 12 },
  retraitDestinationCardSelected: { borderColor: c.formalio500, backgroundColor: c.formalio50 },
  retraitAmountBox: { minHeight: 76, borderRadius: 18, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.white, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, gap: 10 },
  retraitAmountInput: { flex: 1, color: c.surface900, fontFamily: font.black, fontSize: 36, lineHeight: 42, paddingVertical: 8 },
  retraitSummaryCard: { gap: 10, borderColor: c.formalio100, backgroundColor: c.formalio50 },
  versementSummaryCard: { borderColor: c.formalio100, backgroundColor: c.formalio50, padding: 16 },
  versementSummaryIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: c.white, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: c.formalio100 },
  versementRowCard: { padding: 13 },
  versementRowIcon: { width: 38, height: 38, borderRadius: 13, backgroundColor: c.danger50, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  choiceCard: { minWidth: 0, minHeight: 74, borderRadius: 14, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.white, alignItems: 'center', justifyContent: 'center', padding: 10, gap: 6, shadowColor: c.surface900, shadowOpacity: 0.035, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, elevation: 1 },
  choiceIcon: { width: 30, height: 30, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  mobileMoneyChoiceIcon: { borderWidth: 1, borderColor: c.surface200, shadowColor: c.surface900, shadowOpacity: 0.06, shadowRadius: 6, elevation: 1 },
  choiceSelected: { borderColor: c.formalio300, backgroundColor: c.formalio50 },
  choiceSelectedExpense: { borderColor: c.danger200, backgroundColor: c.danger50 },
  selectChip: { minHeight: 36, borderRadius: 10, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.white, paddingHorizontal: 12, paddingVertical: 8, alignItems: 'center', justifyContent: 'center' },
  selectChipActive: { borderColor: c.formalio300, backgroundColor: c.formalio50 },
  selectChipExpenseActive: { borderColor: c.danger200, backgroundColor: c.danger50 },
  treasuryHero: { borderRadius: 26, padding: 16, overflow: 'hidden' },
  glassIcon: { width: 48, height: 48, borderRadius: 16, backgroundColor: 'rgba(255,255,255,.1)', alignItems: 'center', justifyContent: 'center' },
  glassIconSmall: { width: 40, height: 40, borderRadius: 13, backgroundColor: 'rgba(255,255,255,.1)', alignItems: 'center', justifyContent: 'center' },
  metricCard: { borderRadius: 18, borderWidth: 1, padding: 14 },
  insightBox: { borderRadius: 18, borderWidth: 1, borderColor: c.formalio200, backgroundColor: c.formalio50, padding: 12 },
  scoreHero: { borderRadius: 26, padding: 16, overflow: 'hidden' },
  scoreRingCenter: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, alignItems: 'center', justifyContent: 'center' },
  scoreChip: { backgroundColor: 'rgba(255,255,255,.1)', borderRadius: 16, padding: 9, marginTop: 14 },
  metricIcon: { width: 32, height: 32, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  adviceCard: { flexDirection: 'row', gap: 12, borderRadius: 18, borderWidth: 1, borderColor: c.formalio200, backgroundColor: c.formalio50, padding: 14 },
  loanEligible: { flexDirection: 'row', gap: 12, borderRadius: 18, borderWidth: 1, borderColor: c.gold200, backgroundColor: c.gold50, padding: 14 },
  smallRound: { width: 34, height: 34, borderRadius: 17, backgroundColor: c.surface100, alignItems: 'center', justifyContent: 'center' },
  durationButton: { minHeight: 36, borderRadius: 12, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.surface50, alignItems: 'center', justifyContent: 'center' },
  durationButtonActive: { backgroundColor: c.formalio700, borderColor: c.formalio700, shadowColor: c.formalio900, shadowOpacity: 0.12, shadowRadius: 8, elevation: 2 },
  loanDrawer: { maxHeight: '92%', backgroundColor: c.white, borderTopLeftRadius: 26, borderTopRightRadius: 26, overflow: 'hidden' },
  loanDrawerHeader: { paddingHorizontal: 18, paddingTop: 10, paddingBottom: 18 },
  drawerHandle: { alignSelf: 'center', width: 38, height: 4, borderRadius: 4, backgroundColor: 'rgba(255,255,255,.32)', marginBottom: 14 },
  loanDrawerContent: { padding: 16, gap: 14, paddingBottom: 22 },
  loanEligibilityCard: { borderRadius: 20, borderWidth: 1, borderColor: c.formalio200, backgroundColor: c.formalio50, padding: 14, shadowColor: c.formalio900, shadowOpacity: 0.05, shadowRadius: 10, elevation: 1 },
  loanPurposeSelect: { minHeight: 44, borderRadius: 13, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.surface50, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  loanPurposeMenu: { marginTop: 8, borderRadius: 14, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.white, overflow: 'hidden' },
  loanPurposeItem: { minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: c.surface100 },
  loanCalcCard: { minHeight: 112, borderRadius: 18, borderWidth: 1, padding: 12, overflow: 'hidden' },
  loanCalcIcon: { width: 31, height: 31, borderRadius: 11, alignItems: 'center', justifyContent: 'center', shadowColor: c.surface900, shadowOpacity: 0.05, shadowRadius: 8, elevation: 1 },
  validationRow: { alignItems: 'flex-start', gap: 8, marginTop: 7 },
  validationDot: { width: 8, height: 8, borderRadius: 4, marginTop: 4 },
  termsRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, borderRadius: 16, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.surface50, padding: 12 },
  checkbox: { width: 22, height: 22, borderRadius: 7, borderWidth: 1, borderColor: c.surface300, backgroundColor: c.white, alignItems: 'center', justifyContent: 'center' },
  checkboxActive: { borderColor: c.formalio700, backgroundColor: c.formalio700 },
  loanStickyFooter: { borderTopWidth: 1, borderTopColor: c.surface200, backgroundColor: c.white, padding: 14, shadowColor: c.surface950, shadowOpacity: 0.08, shadowRadius: 16, shadowOffset: { width: 0, height: -8 }, elevation: 8 },
  loanSuccessCard: { padding: 22, alignItems: 'center' },
  successSummary: { width: '100%', borderRadius: 16, backgroundColor: c.surface50, padding: 12, marginTop: 16, marginBottom: 16 },
  infoCallout: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, borderRadius: 16, borderWidth: 1, borderColor: c.info200, backgroundColor: c.info50, padding: 12 },
  exportButton: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: c.formalio700, borderRadius: 9, paddingHorizontal: 11, paddingVertical: 7 },
  reportHero: { borderRadius: 18, padding: 16, marginBottom: 16 },
  reportTap: { width: '100%' },
  reportRow: { width: '100%', minHeight: 78, flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: c.white, borderRadius: 16, borderWidth: 1, borderColor: c.surface200, paddingHorizontal: 12, paddingVertical: 12, shadowColor: c.surface900, shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 2 },
  reportRowBody: { flex: 1, minWidth: 0 },
  reportRowAction: { flexShrink: 0, gap: 6 },
  reportBadge: { flexShrink: 0 },
  loanEmptyState: { flexDirection: 'row', alignItems: 'flex-start', gap: 11, borderRadius: 18, borderWidth: 1, borderColor: c.gold200, backgroundColor: c.gold50, padding: 14 },
  loanTrackingCard: { borderRadius: 18, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.white, padding: 14, shadowColor: c.surface900, shadowOpacity: 0.04, shadowRadius: 10, elevation: 1 },
  loanStatusBadge: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: 999, paddingHorizontal: 9, paddingVertical: 5 },
  loanDetailHero: { borderRadius: 24, padding: 16, overflow: 'hidden' },
  loanTimelineRow: { gap: 10, alignItems: 'flex-start', borderTopWidth: 1, borderTopColor: c.surface100, paddingVertical: 10 },
  loanTimelineNode: { width: 30, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center' },
  reportLine: { justifyContent: 'space-between', paddingVertical: 10 },
  reportStamp: { flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 12, backgroundColor: c.formalio50, padding: 10, marginTop: 12 },
  reportInsightCallout: { flexDirection: 'row', gap: 10, borderRadius: 18, borderWidth: 1, borderColor: c.formalio200, backgroundColor: c.formalio50, padding: 13 },
  reportDetailHero: { borderRadius: 24, padding: 16, overflow: 'hidden' },
  reportScoreRing: { width: 58, height: 58, borderRadius: 29, borderWidth: 1, borderColor: 'rgba(255,255,255,.22)', backgroundColor: 'rgba(255,255,255,.1)', alignItems: 'center', justifyContent: 'center' },
  reportMetricCard: { minHeight: 112, padding: 12 },
  reportMetricAccent: { width: 20, height: 3, borderRadius: 3 },
  reportDocumentCard: { padding: 18, marginBottom: 14 },
  reportExportPanel: { padding: 16, marginBottom: 12, borderColor: c.formalio200 },
  exportBadge: { width: 40, height: 40, borderRadius: 13, backgroundColor: c.formalio50, alignItems: 'center', justifyContent: 'center' },
  exportFormatMini: { minHeight: 42, borderRadius: 13, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.surface50, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, paddingHorizontal: 8 },
  moneyLogo: { width: 48, height: 48, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  syncRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: c.surface50, borderRadius: 11, padding: 10 },
  notificationCard: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, borderRadius: 14, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.white, padding: 14 },
  notificationIcon: { width: 36, height: 36, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  unreadDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: c.formalio500, marginTop: 6 },
  aiHeaderCard: { flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 18, borderWidth: 1, borderColor: c.formalio200, backgroundColor: c.formalio50, padding: 12, marginBottom: 16 },
  insightCard: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, borderRadius: 18, borderWidth: 1, padding: 14 },
  taxAlert: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, borderRadius: 18, borderWidth: 1, borderColor: c.amber200, backgroundColor: c.amber50, padding: 14, marginBottom: 16 },
  taxButton: { alignSelf: 'flex-start', borderRadius: 9, backgroundColor: c.amber500, paddingHorizontal: 12, paddingVertical: 7, marginTop: 9 },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  profileHero: { paddingHorizontal: 18, paddingTop: 54, paddingBottom: 26, minHeight: 178, overflow: 'hidden', justifyContent: 'flex-end' },
  profileTopActions: { position: 'absolute', top: 18, right: 16, zIndex: 3 },
  profileAvatar: { width: 72, height: 72, borderRadius: 36, backgroundColor: 'rgba(255,255,255,.1)', borderWidth: 2, borderColor: 'rgba(255,255,255,.22)', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  profileCheck: { position: 'absolute', right: -2, bottom: -2, width: 24, height: 24, borderRadius: 12, backgroundColor: c.formalio500, borderWidth: 2, borderColor: c.formalio800, alignItems: 'center', justifyContent: 'center' },
  profileCompletionCard: { marginBottom: 12, borderColor: c.formalio200 },
  profileEditorCard: { marginBottom: 12, padding: 16, borderColor: c.surface200, shadowColor: c.surface900, shadowOpacity: 0.06, shadowRadius: 12, elevation: 2 },
  profileEditorHeader: { gap: 12, marginBottom: 14 },
  profileEditorHeaderText: { width: '100%' },
  profileEditorActions: { alignSelf: 'stretch', justifyContent: 'flex-end', gap: 8, flexWrap: 'wrap' },
  profileMiniButton: { minWidth: 112, minHeight: 40, borderRadius: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingHorizontal: 14, backgroundColor: c.surface100, borderWidth: 1, borderColor: c.surface200 },
  profileMiniButtonPrimary: { backgroundColor: c.formalio700, borderColor: c.formalio700, shadowColor: c.formalio900, shadowOpacity: 0.14, shadowRadius: 10, elevation: 3 },
  profileActionButton: { minWidth: 132, minHeight: 42, borderRadius: 14, shadowOpacity: 0.08 },
  profileEditButton: { alignSelf: 'flex-end', minWidth: 168, minHeight: 42, borderRadius: 14, shadowOpacity: 0.1 },
  avatarSelector: { borderRadius: 16, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.surface50, padding: 12 },
  avatarGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  avatarChoice: { width: 78, minHeight: 96, borderRadius: 16, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.white, alignItems: 'center', justifyContent: 'center', gap: 5, paddingVertical: 8 },
  avatarChoiceSelected: { borderColor: c.formalio500, backgroundColor: c.formalio50, transform: [{ scale: 1.02 }] },
  coverThemeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  coverThemeChoice: { flexGrow: 1, minWidth: 132, borderRadius: 14, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.white, padding: 9, gap: 7 },
  coverThemeChoiceSelected: { borderColor: c.formalio500, backgroundColor: c.formalio50 },
  coverThemeSwatch: { height: 34, borderRadius: 10 },
  profileInfoRow: { gap: 10, minHeight: 50, paddingVertical: 7, borderTopWidth: 1, borderTopColor: c.surface100 },
  profileMenu: { backgroundColor: c.white, borderRadius: 20, borderWidth: 1, borderColor: c.surface200, overflow: 'hidden', shadowColor: c.surface900, shadowOpacity: 0.07, shadowRadius: 14, elevation: 3 },
  profileMenuTap: { width: '100%' },
  profileMenuItem: { width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 11, minHeight: 58, paddingHorizontal: 14, paddingVertical: 12 },
  profileMenuIcon: { width: 32, height: 32, borderRadius: 11, backgroundColor: c.surface50, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  profileMenuLabel: { flex: 1, minWidth: 0, color: c.surface700, fontSize: 13, lineHeight: 17 },
  profileMenuBadge: { flexShrink: 0 },
  logoutButtonWrap: { alignItems: 'center', marginTop: 20 },
  logoutButton: { width: 240, minHeight: 48, borderRadius: 999, backgroundColor: c.danger500, borderWidth: 1, borderColor: c.danger500, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingHorizontal: 18, shadowColor: c.danger500, shadowOpacity: 0.14, shadowRadius: 14, shadowOffset: { width: 0, height: 6 }, elevation: 3 },
  logoutButtonPressed: { opacity: 0.88, transform: [{ scale: 0.98 }] },
  logoutButtonText: { color: c.white, fontSize: 14 },
  settingsList: { backgroundColor: c.white, borderRadius: 18, borderWidth: 1, borderColor: c.surface200, overflow: 'hidden', marginBottom: 16 },
  settingsItem: { gap: 12, paddingHorizontal: 16, paddingVertical: 14 },
  languageChoice: { minHeight: 46, borderRadius: 14, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.surface50, alignItems: 'center', justifyContent: 'center' },
  languageChoiceActive: { borderColor: c.formalio500, backgroundColor: c.formalio50 },
  switchTrack: { width: 44, height: 24, borderRadius: 12, backgroundColor: c.surface300, padding: 4 },
  switchThumb: { width: 16, height: 16, borderRadius: 8, backgroundColor: c.white },
  securityCallout: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, borderRadius: 14, borderWidth: 1, borderColor: c.formalio200, backgroundColor: c.formalio50, padding: 14 },
  subscriptionHero: { borderRadius: 18, padding: 20, alignItems: 'center', marginBottom: 16 },
  renewalPill: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: 'rgba(255,255,255,.1)', borderRadius: 999, paddingHorizontal: 12, paddingVertical: 6, marginTop: 12 },
  helpRow: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: c.white, borderWidth: 1, borderColor: c.surface200, borderRadius: 14, padding: 14 },
  referralCard: { alignItems: 'center', borderRadius: 18, borderWidth: 1, borderColor: c.gold200, padding: 20, marginBottom: 16 },
  copyCode: { backgroundColor: c.gold500, borderRadius: 9, paddingHorizontal: 16, paddingVertical: 9, marginTop: 12 },
  kycCard: { marginBottom: 12, padding: 15, borderColor: c.formalio200 },
  kycStatusPill: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: 999, paddingHorizontal: 9, paddingVertical: 5 },
  kycStepper: { gap: 7, paddingVertical: 12 },
  kycStepDot: { width: 28, height: 28, borderRadius: 14, backgroundColor: c.surface100, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: c.surface200 },
  kycStepDotActive: { backgroundColor: c.formalio700, borderColor: c.formalio700 },
  kycStepBody: { borderRadius: 18, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.white, padding: 13, marginBottom: 12 },
  kycChoice: { minHeight: 48, borderRadius: 13, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.surface50, alignItems: 'center', justifyContent: 'center', padding: 8 },
  kycChoiceActive: { borderColor: c.formalio300, backgroundColor: c.formalio50 },
  kycUploadTile: { minHeight: 136, borderRadius: 16, borderWidth: 1, borderColor: c.surface200, overflow: 'hidden', justifyContent: 'center' },
  kycUploadInner: { minHeight: 136, alignItems: 'center', justifyContent: 'center', padding: 12 },
  kycUploadButton: { flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: 999, backgroundColor: c.white, borderWidth: 1, borderColor: c.surface200, paddingHorizontal: 9, paddingVertical: 6 },
  kycReviewBox: { borderRadius: 14, backgroundColor: c.surface50, padding: 12 },
  kycStatusHero: { borderRadius: 18, padding: 16 },
  kycStatusRow: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 9, borderRadius: 13, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.white, paddingHorizontal: 12 },
  pnlHero: { borderRadius: 26, padding: 16, overflow: 'hidden' },
  glassMetric: { backgroundColor: 'rgba(255,255,255,.1)', borderRadius: 12, padding: 10, marginTop: 14 },
  aiInsightsBanner: { flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 18, borderWidth: 1, borderColor: c.info200, backgroundColor: c.info50, padding: 12 },
  aiBannerIcon: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  accQuick: { flexDirection: 'row', alignItems: 'center', gap: 10, borderRadius: 14, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.white, padding: 12 },
  aiMiniButton: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: c.formalio700, borderRadius: 9, paddingHorizontal: 10, paddingVertical: 7 },
  salesHero: { borderRadius: 26, padding: 16 },
  liveDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: c.formalio500 },
  tinyDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: c.formalio500 },
  anomalyRow: { gap: 8, borderTopWidth: 1, borderTopColor: c.surface100, paddingVertical: 9 },
  aiAccountantHero: { borderRadius: 26, padding: 16, overflow: 'hidden' },
  optimizationBox: { borderRadius: 18, borderWidth: 1, borderColor: c.gold200, backgroundColor: c.gold50, padding: 12 },
  aiReportRow: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: c.white, borderRadius: 18, borderWidth: 1, borderColor: c.surface200, padding: 12 },
  modalBackdrop: { flex: 1, justifyContent: 'flex-end', padding: 16, backgroundColor: 'rgba(15,23,42,.72)' },
  modalCard: { width: '100%', maxWidth: 430, alignSelf: 'center', borderRadius: 26, backgroundColor: c.white, overflow: 'hidden' },
  assistantModal: { maxHeight: '90%', backgroundColor: c.white },
  assistantHeader: { padding: 16, backgroundColor: c.white, borderBottomWidth: 1, borderBottomColor: c.surface200 },
  assistantHeaderIcon: { width: 36, height: 36, borderRadius: 12, backgroundColor: c.formalio50, alignItems: 'center', justifyContent: 'center' },
  closeButton: { width: 32, height: 32, borderRadius: 16, backgroundColor: c.surface100, alignItems: 'center', justifyContent: 'center' },
  messageRow: { flexDirection: 'row' },
  messageBubble: { maxWidth: '86%', borderRadius: 18, padding: 13 },
  userBubble: { backgroundColor: c.formalio700, borderBottomRightRadius: 5 },
  aiBubble: { backgroundColor: c.white, borderWidth: 1, borderColor: c.surface200, borderBottomLeftRadius: 5 },
  suggestions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
  suggestionChip: { flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: c.formalio50, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  assistantScroll: { maxHeight: 492, backgroundColor: c.surface50 },
  assistantActionBar: { backgroundColor: c.white, borderTopWidth: 1, borderTopColor: c.surface200, paddingHorizontal: 12, paddingTop: 8 },
  assistantActionPill: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: c.surface50, borderWidth: 1, borderColor: c.surface200, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 7 },
  assistantActionPillActive: { backgroundColor: c.formalio50, borderColor: c.formalio200 },
  voiceNotePanel: { borderTopWidth: 1, borderTopColor: c.surface200, backgroundColor: c.white, paddingHorizontal: 14, paddingVertical: 12 },
  recordingMicWrap: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' },
  voicePulseRing: { position: 'absolute', width: 42, height: 42, borderRadius: 21, backgroundColor: c.formalio700 },
  recordingMic: { width: 34, height: 34, borderRadius: 17, backgroundColor: c.formalio700, alignItems: 'center', justifyContent: 'center' },
  voiceControlButton: { flex: 1, minHeight: 38, borderRadius: 14, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.surface50, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingHorizontal: 10 },
  voiceStopButton: { backgroundColor: c.danger500, borderColor: c.danger500 },
  voiceSendButton: { backgroundColor: c.formalio700, borderColor: c.formalio700 },
  assistantInputArea: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: c.white, borderTopWidth: 1, borderTopColor: c.surface200, padding: 12 },
  assistantMicButton: { width: 42, height: 42, borderRadius: 21, backgroundColor: c.formalio50, borderWidth: 1, borderColor: c.formalio200, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  assistantMicButtonRecording: { backgroundColor: c.danger500, borderColor: c.danger500 },
  assistantMic: { width: 40, height: 40, borderRadius: 20, backgroundColor: c.surface100, alignItems: 'center', justifyContent: 'center' },
  assistantInput: { flex: 1, minHeight: 42, borderRadius: 21, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.surface50, paddingHorizontal: 14, justifyContent: 'center' },
  sendButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: c.formalio700, alignItems: 'center', justifyContent: 'center' },
  voiceHeader: { justifyContent: 'space-between', padding: 16, borderBottomWidth: 1, borderBottomColor: c.surface200 },
  voiceBody: { padding: 22, alignItems: 'center' },
  waveformBox: { width: '100%', height: 86, alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  transcriptBox: { width: '100%', backgroundColor: c.surface50, borderRadius: 14, padding: 12 },
  parsedCard: { width: '100%', borderRadius: 18, borderWidth: 1, borderColor: c.formalio200, backgroundColor: c.formalio50, padding: 14, marginBottom: 14 },
  refreshButton: { width: 50, minHeight: 46, borderRadius: 16, backgroundColor: c.surface100, alignItems: 'center', justifyContent: 'center' },
  downloadHeader: { padding: 18 },
  docPreview: { borderRadius: 18, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.surface50, padding: 14, marginBottom: 16 },
  docPaper: { backgroundColor: c.white, borderRadius: 9, padding: 14, shadowColor: c.surface900, shadowOpacity: 0.06, shadowRadius: 8, elevation: 1 },
  skeleton: { height: 8, borderRadius: 8, backgroundColor: c.surface200 },
  formatButton: { alignItems: 'center', borderWidth: 2, borderColor: c.surface200, borderRadius: 18, backgroundColor: c.white, padding: 14, marginBottom: 16 },
  formatIcon: { width: 50, height: 50, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginBottom: 8 },
  secondaryAction: { alignItems: 'center', gap: 5, backgroundColor: c.surface50, borderRadius: 13, padding: 12 },
  downloadProgress: { width: '100%', borderRadius: 18, backgroundColor: c.surface50, padding: 14, marginTop: 22 },
  completeFile: { width: '100%', flexDirection: 'row', gap: 12, alignItems: 'center', borderRadius: 18, borderWidth: 1, borderColor: c.formalio200, backgroundColor: c.formalio50, padding: 14, marginBottom: 16 },
  ocrModal: { maxHeight: '92%', backgroundColor: c.white },
  ocrHeader: { padding: 16 },
  ocrDropZone: { minHeight: 58, borderRadius: 16, borderWidth: 1, borderStyle: 'dashed', borderColor: c.info100, backgroundColor: c.info50, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 14, paddingVertical: 10 },
  ocrCameraBox: { height: 284, borderRadius: 22, backgroundColor: c.surface900, overflow: 'hidden', alignItems: 'center', justifyContent: 'center' },
  ocrFrame: { position: 'absolute', left: 34, right: 34, top: 42, bottom: 42, borderRadius: 18 },
  ocrCorner: { position: 'absolute', width: 34, height: 34, borderColor: c.formalio300 },
  ocrCornerTopLeft: { left: 0, top: 0, borderLeftWidth: 3, borderTopWidth: 3, borderTopLeftRadius: 18 },
  ocrCornerTopRight: { right: 0, top: 0, borderRightWidth: 3, borderTopWidth: 3, borderTopRightRadius: 18 },
  ocrCornerBottomLeft: { left: 0, bottom: 0, borderLeftWidth: 3, borderBottomWidth: 3, borderBottomLeftRadius: 18 },
  ocrCornerBottomRight: { right: 0, bottom: 0, borderRightWidth: 3, borderBottomWidth: 3, borderBottomRightRadius: 18 },
  ocrScanLine: { position: 'absolute', left: 42, right: 42, top: 116, height: 3, borderRadius: 3, backgroundColor: c.formalio400, shadowColor: c.formalio400, shadowOpacity: 1, shadowRadius: 14 },
  ocrCameraOverlay: { ...StyleSheet.absoluteFillObject, alignItems: 'center', justifyContent: 'center', padding: 18 },
  ocrPermissionCard: { width: '86%', borderRadius: 18, backgroundColor: c.white, padding: 16, alignItems: 'center' },
  ocrProcessingCard: { borderRadius: 18, backgroundColor: c.white, padding: 16, alignItems: 'center', minWidth: 210 },
  ocrSuccessBadge: { flexDirection: 'row', alignItems: 'center', gap: 7, borderRadius: 999, backgroundColor: c.formalio600, paddingHorizontal: 13, paddingVertical: 8 },
  ocrSignalCard: { padding: 12 },
  ocrResultCard: { borderRadius: 18, borderWidth: 1, borderColor: c.formalio200, backgroundColor: c.formalio50, padding: 14 },
  ocrDataCell: { borderRadius: 12, backgroundColor: c.white, borderWidth: 1, borderColor: c.formalio100, padding: 10 },
  ocrToolButton: { width: 44, height: 44, borderRadius: 14, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.white, alignItems: 'center', justifyContent: 'center' },
  ocrManualFallback: { minHeight: 42, borderRadius: 13, borderWidth: 1, borderColor: c.surface200, backgroundColor: c.surface50, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 },
  scannerBox: { height: 224, marginTop: 16, borderRadius: 18, backgroundColor: c.surface900, overflow: 'hidden', alignItems: 'center', justifyContent: 'center' },
  scannerFrame: { position: 'absolute', left: 24, right: 24, top: 24, bottom: 24, borderRadius: 13, borderWidth: 2, borderColor: c.formalio300, borderStyle: 'dashed' },
  scanLine: { position: 'absolute', left: 24, right: 24, top: 80, height: 2, backgroundColor: c.formalio400, shadowColor: c.formalio400, shadowOpacity: 1, shadowRadius: 12 },
  detectedBox: { borderRadius: 18, backgroundColor: c.formalio50, padding: 14, marginTop: 16 },
  detectedCell: { alignItems: 'center', backgroundColor: c.white, borderRadius: 12, padding: 9, marginTop: 8 },
  confettiLayer: { ...StyleSheet.absoluteFillObject, zIndex: 250 },
});
